
export enum ReportType {

    COMPANY_ANALYSIS= "COMPANY_ANALYSIS",
    BRAND_ANALYSIS= "BRAND_ANALYSIS",
    INVESTMENT_FEASIBILITY= "INVESTMENT_FEASIBILITY",
    MARKET_ANALYSIS= "MARKET_ANALYSIS",
    SHIP_VALUATION= "SHIP_VALUATION",
    MACHINE_VALUATION= "MACHINE_VALUATION",
    HOTEL_FEASIBILITY= "HOTEL_FEASIBILITY",
    HOTEL_VALUATION= "HOTEL_VALUATION",
    FACTORY_VALUATION= "FACTORY_VALUATION",
    REAL_ESTATE_VALUATION= "REAL_ESTATE_VALUATION",
    INFRASTRUCTURE_INVESTMENT_VALUATION= "INFRASTRUCTURE_INVESTMENT_VALUATION",
}