
export enum CompanyFileType {

    VEHICLE_LICENCE = "VEHICLE_LICENCE",
    REAL_ESTATE_DEED = "REAL_ESTATE_DEED",
    DEPOSIT = "DEPOSIT",
    STOCK = "STOCK",
    RISK_REPORT = "RISK_REPORT",
    CHECK_REPORT = "CHECK_REPORT",
    PERSONAL_RISK_REPORT = "PERSONAL_RISK_REPORT",
    TAX_DECLARATION = "TAX_DECLARATION",
    DETAILED_MIZAN = "DETAILED_MIZAN",
    TAX_CERTIFICATION = "TAX_CERTIFICATION",
    INDEPENDENT_AUDIT_REPORT = "INDEPENDENT_AUDIT_REPORT",
    TRADE_REGISTRY_NEWSPAPER = "TRADE_REGISTRY_NEWSPAPER",
    ACTIVITY_CERTIFICATION = "ACTIVITY_CERTIFICATION",
    SIGNATURE_CIRCULAR = "SIGNATURE_CIRCULAR",
    SOCIAL_SECURITY_REGISTRY = "SOCIAL_SECURITY_REGISTRY",
    PERFORMAL_INVOICE = "PERFORMAL_INVOICE",
    FEASIBILITY_REPORT = "FEASIBILITY_REPORT",
    BUILDING_LAND_PERMIT = "BUILDING_LAND_PERMIT",
    INVESTMENT_INCENTIVE_CERTIFICATE = "INVESTMENT_INCENTIVE_CERTIFICATE",
}