export enum PartnershipDuty {
    MANAGER = "MANAGER",
    BOARD_MEMBER = "BOARD_MEMBER",
    PARTNER = "PARTNER",
    LEGAL_REPRESENTATIVE = "LEGAL_REPRESENTATIVE",
    LIMITED_AUTHORIZED_PARTNER = "LIMITED_AUTHORIZED_PARTNER",
    NOT_AUTHORIZED_PARTNER = "NOT_AUTHORIZED_PARTNER",
}